package:
  name: "transposon_annotation_tools_sinefinder"
  version: "1.0.1"

build:
  number: 0

requirements:
  run:
    - python 2.7

about:
  home: https://github.com/DerKevinRiehl/transposon_annotation_tools
  license: BSD
  license_family: BSD
  summary: "SineFinderv1.0.1, tool developed by Wenke et al. (2011) Plant Cell, https://doi.org/10.1105/tpc.111.088682"
  doc_url: https://github.com/DerKevinRiehl/transposon_annotation_tools
  dev_url: https://github.com/DerKevinRiehl/transposon_annotation_tools
  description: A set of bioconda packages for transposon annotations. During my masterthesis I downloaded lots of these tools and I want to make it easier for the research community to install and run these softwares as bioconda packages from command line. 
