#!/usr/bin/env python

from shutil import copyfile, rmtree
from os import path
import os.path
import sys

# Methods
def getArgument(args, title):
    for i in range(0, len(args)):
        if(args[i].startswith("-"+title)):
            if(i<len(args)-1):
                return args[i+1]
            else:
                return ""
    return ""

args = sys.argvs

# Parameters
resultFolder = getArgument(args, "resultFolder")
fastaFile    = getArgument(args, "fastaFile")

# Localize share folder
script_dir = os.path.dirname(__file__)
parent_dir = os.path.abspath(os.path.join(script_dir, os.pardir))
share_dir  = os.path.join(parent_dir, "share", "proteinNCBICDD1000")
selec_dir  = os.path.join(parent_dir, "share", "proteinNCBICDD1000", "selection")

# Create results folder
if(path.isdir(resultFolder)):
    rmtree(resultFolder)
os.mkdir(resultFolder)

# For all Libraries run
for i in range(1,50+1):
    os.system("rpstblastn -query "+os.path.abspath(fastaFile)+" -db "+os.path.join(selec_dir,"Selection1000Library"+"{0:0=3d}".format(i))+" -outfmt \"7 stitle evalue qstart qend\" -evalue 0.01 -out "+os.path.abspath(os.path.join(resultFolder,"Result"+"{0:0=3d}".format(i)+".txt")))
    print("finished scan ",i," of 50")
print("finished completely...")